# Generated by Django 4.0.2 on 2022-06-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_remove_form_see_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='confirmation_message',
            field=models.CharField(default='Your response has been submitted! Thank you for your participation!', max_length=10000),
        ),
    ]
